// Code generated by tools/enumgen from schemas/common/v1/ids.schema.json. DO NOT EDIT.

package config

type Channel string

const (
	ChannelWebRTC    Channel = "webrtc"
	ChannelTelephony Channel = "telephony"
	ChannelLongForm  Channel = "long_form"
)

// AllChannels is every member, in schema order.
var AllChannels = []Channel{
	ChannelWebRTC,
	ChannelTelephony,
	ChannelLongForm,
}

func (v Channel) Valid() bool {
	for _, m := range AllChannels {
		if v == m {
			return true
		}
	}
	return false
}
