// Code generated by tools/enumgen from schemas/config/v1/resolved-session-config.schema.json. DO NOT EDIT.

package config

type EgressLayout string

const (
	LayoutTrack          EgressLayout = "track"
	LayoutTrackComposite EgressLayout = "track_composite"
	LayoutRoomComposite  EgressLayout = "room_composite"
)

// AllEgressLayouts is every member, in schema order.
var AllEgressLayouts = []EgressLayout{
	LayoutTrack,
	LayoutTrackComposite,
	LayoutRoomComposite,
}

func (v EgressLayout) Valid() bool {
	for _, m := range AllEgressLayouts {
		if v == m {
			return true
		}
	}
	return false
}
