// Code generated by tools/enumgen from schemas/config/v1/resolved-session-config.schema.json. DO NOT EDIT.

package config

type AgentMode string

const (
	ModeCascaded       AgentMode = "cascaded"
	ModeHalfCascade    AgentMode = "half_cascade"
	ModeSpeechToSpeech AgentMode = "speech_to_speech"
)

// AllAgentModes is every member, in schema order.
var AllAgentModes = []AgentMode{
	ModeCascaded,
	ModeHalfCascade,
	ModeSpeechToSpeech,
}

func (v AgentMode) Valid() bool {
	for _, m := range AllAgentModes {
		if v == m {
			return true
		}
	}
	return false
}
