// Code generated by tools/enumgen from schemas/config/v1/resolved-session-config.schema.json. DO NOT EDIT.

package config

type PrivacyMode string

const (
	PrivacyOpen         PrivacyMode = "open"
	PrivacySealed       PrivacyMode = "sealed"
	PrivacyTrustedAgent PrivacyMode = "trusted_agent"
)

// AllPrivacyModes is every member, in schema order.
var AllPrivacyModes = []PrivacyMode{
	PrivacyOpen,
	PrivacySealed,
	PrivacyTrustedAgent,
}

func (v PrivacyMode) Valid() bool {
	for _, m := range AllPrivacyModes {
		if v == m {
			return true
		}
	}
	return false
}
