// Code generated by tools/enumgen from schemas/common/v1/ids.schema.json. DO NOT EDIT.

package config

type Role string

const (
	RoleParticipant Role = "participant"
	RolePresenter   Role = "presenter"
	RoleObserver    Role = "observer"
	RoleAgent       Role = "agent"
	RoleRecorder    Role = "recorder"
)

// AllRoles is every member, in schema order.
var AllRoles = []Role{
	RoleParticipant,
	RolePresenter,
	RoleObserver,
	RoleAgent,
	RoleRecorder,
}

func (v Role) Valid() bool {
	for _, m := range AllRoles {
		if v == m {
			return true
		}
	}
	return false
}
