// Code generated by tools/enumgen from schemas/config/v1/resolved-session-config.schema.json. DO NOT EDIT.

package config

type RecordingStart string

const (
	StartAtSessionCreate RecordingStart = "session_create"
	StartAtFirstPublish  RecordingStart = "first_publish"
)

// AllRecordingStarts is every member, in schema order.
var AllRecordingStarts = []RecordingStart{
	StartAtSessionCreate,
	StartAtFirstPublish,
}

func (v RecordingStart) Valid() bool {
	for _, m := range AllRecordingStarts {
		if v == m {
			return true
		}
	}
	return false
}
