// Code generated by tools/enumgen from schemas/config/v1/resolved-session-config.schema.json. DO NOT EDIT.

package config

type TurnStrategy string

const (
	TurnAuto                TurnStrategy = "auto"
	TurnVAD                 TurnStrategy = "vad"
	TurnProviderEndpointing TurnStrategy = "provider_endpointing"
	TurnSemantic            TurnStrategy = "semantic"
	TurnServerVAD           TurnStrategy = "server_vad"
	TurnManual              TurnStrategy = "manual"
)

// AllTurnStrategies is every member, in schema order.
var AllTurnStrategies = []TurnStrategy{
	TurnAuto,
	TurnVAD,
	TurnProviderEndpointing,
	TurnSemantic,
	TurnServerVAD,
	TurnManual,
}

func (v TurnStrategy) Valid() bool {
	for _, m := range AllTurnStrategies {
		if v == m {
			return true
		}
	}
	return false
}
