package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

type target struct {
	Schema  string   // path under schemas/
	Pointer []string // where the enum lives in that schema
	Package string   // Go package name
	Type    string   // Go type name
	Prefix  string   // constant name prefix
	Out     string   // file to write, relative to the go module root
	AllName string   // name of the generated slice of every member
	TypeDoc string
}

var targets = []target{
	{
		Schema: "errors/v1/error.schema.json", Pointer: []string{"$defs", "ErrorCode", "enum"},
		Package: "errs", Type: "ErrorCode", Prefix: "Code",
		Out: "internal/errs/codes_gen.go", AllName: "AllErrorCodes",
	},
	{
		Schema: "errors/v1/error.schema.json", Pointer: []string{"properties", "stage", "enum"},
		Package: "errs", Type: "Stage", Prefix: "Stage",
		Out: "internal/errs/stages_gen.go", AllName: "AllStages",
	},
	{
		Schema: "events/v1/envelope.schema.json", Pointer: []string{"$defs", "EventType", "enum"},
		Package: "events", Type: "EventType", Prefix: "Event",
		Out: "internal/events/types_gen.go", AllName: "AllEventTypes",
	},
	{
		Schema: "events/v1/envelope.schema.json", Pointer: []string{"$defs", "AgentState", "enum"},
		Package: "events", Type: "AgentState", Prefix: "Agent",
		Out: "internal/events/states_gen.go", AllName: "AllAgentStates",
	},
	{
		Schema: "common/v1/ids.schema.json", Pointer: []string{"$defs", "Role", "enum"},
		Package: "config", Type: "Role", Prefix: "Role",
		Out: "internal/config/roles_gen.go", AllName: "AllRoles",
	},
	{
		Schema: "common/v1/ids.schema.json", Pointer: []string{"$defs", "Channel", "enum"},
		Package: "config", Type: "Channel", Prefix: "Channel",
		Out: "internal/config/channels_gen.go", AllName: "AllChannels",
	},
	{
		Schema: "config/v1/resolved-session-config.schema.json", Pointer: []string{"properties", "privacyMode", "enum"},
		Package: "config", Type: "PrivacyMode", Prefix: "Privacy",
		Out: "internal/config/privacy_gen.go", AllName: "AllPrivacyModes",
	},
	{
		Schema: "config/v1/resolved-session-config.schema.json", Pointer: []string{"properties", "agent", "properties", "mode", "enum"},
		Package: "config", Type: "AgentMode", Prefix: "Mode",
		Out: "internal/config/modes_gen.go", AllName: "AllAgentModes",
	},
	{
		Schema: "config/v1/resolved-session-config.schema.json", Pointer: []string{"$defs", "Turn", "properties", "strategy", "enum"},
		Package: "config", Type: "TurnStrategy", Prefix: "Turn",
		Out: "internal/config/turn_gen.go", AllName: "AllTurnStrategies",
	},
	{
		Schema: "config/v1/resolved-session-config.schema.json", Pointer: []string{"$defs", "Recording", "properties", "layout", "enum"},
		Package: "config", Type: "EgressLayout", Prefix: "Layout",
		Out: "internal/config/layouts_gen.go", AllName: "AllEgressLayouts",
	},
	{
		Schema: "config/v1/resolved-session-config.schema.json", Pointer: []string{"$defs", "Recording", "properties", "startAt", "enum"},
		Package: "config", Type: "RecordingStart", Prefix: "StartAt",
		Out: "internal/config/start_gen.go", AllName: "AllRecordingStarts",
	},
}

var initialisms = map[string]string{
	"vad": "VAD", "stt": "STT", "tts": "TTS", "llm": "LLM", "mt": "MT",
	"webrtc": "WebRTC", "api": "API", "id": "ID", "url": "URL", "json": "JSON",
}

func goName(prefix, value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool {
		return r == '_' || r == '.' || r == '-'
	})
	var b strings.Builder
	b.WriteString(prefix)
	for _, p := range parts {
		if up, ok := initialisms[strings.ToLower(p)]; ok {
			b.WriteString(up)
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + strings.ToLower(p[1:]))
	}
	return b.String()
}

func enumAt(root string, t target) ([]string, error) {
	b, err := os.ReadFile(filepath.Join(root, t.Schema))
	if err != nil {
		return nil, err
	}
	var doc any
	if err := json.Unmarshal(b, &doc); err != nil {
		return nil, err
	}
	cur := doc
	for _, k := range t.Pointer {
		m, ok := cur.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("%s: %v is not an object at %q", t.Schema, t.Pointer, k)
		}
		cur, ok = m[k]
		if !ok {
			return nil, fmt.Errorf("%s: no %q in %v", t.Schema, k, t.Pointer)
		}
	}
	raw, ok := cur.([]any)
	if !ok {
		return nil, fmt.Errorf("%s: %v is not an enum", t.Schema, t.Pointer)
	}
	out := make([]string, 0, len(raw))
	for _, v := range raw {
		s, ok := v.(string)
		if !ok {
			return nil, fmt.Errorf("%s: %v has a non-string member", t.Schema, t.Pointer)
		}
		out = append(out, s)
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("%s: %v is empty", t.Schema, t.Pointer)
	}
	return out, nil
}

func render(t target, values []string) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by tools/enumgen from schemas/%s. DO NOT EDIT.\n\n", t.Schema)
	fmt.Fprintf(&b, "package %s\n\n", t.Package)
	fmt.Fprintf(&b, "type %s string\n\n", t.Type)
	fmt.Fprintf(&b, "const (\n")
	for _, v := range values {
		fmt.Fprintf(&b, "\t%s %s = %q\n", goName(t.Prefix, v), t.Type, v)
	}
	fmt.Fprintf(&b, ")\n\n")
	fmt.Fprintf(&b, "// %s is every member, in schema order.\n", t.AllName)
	fmt.Fprintf(&b, "var %s = []%s{\n", t.AllName, t.Type)
	for _, v := range values {
		fmt.Fprintf(&b, "\t%s,\n", goName(t.Prefix, v))
	}
	fmt.Fprintf(&b, "}\n\n")
	fmt.Fprintf(&b, "func (v %s) Valid() bool {\n\tfor _, m := range %s {\n\t\tif v == m {\n\t\t\treturn true\n\t\t}\n\t}\n\treturn false\n}\n", t.Type, t.AllName)
	return format.Source(b.Bytes())
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: enumgen <schemas-dir> <go-module-root>")
		os.Exit(2)
	}
	schemaRoot, goRoot := os.Args[1], os.Args[2]

	for _, t := range targets {
		values, err := enumAt(schemaRoot, t)
		if err != nil {
			fmt.Fprintf(os.Stderr, "enumgen: %v\n", err)
			os.Exit(1)
		}
		src, err := render(t, values)
		if err != nil {
			fmt.Fprintf(os.Stderr, "enumgen: render %s: %v\n", t.Out, err)
			os.Exit(1)
		}
		out := filepath.Join(goRoot, t.Out)
		if err := os.WriteFile(out, src, 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "enumgen: write %s: %v\n", out, err)
			os.Exit(1)
		}
		fmt.Printf("  %-34s %2d values\n", t.Out, len(values))
	}
}
