// Code generated by tools/enumgen from schemas/events/v1/envelope.schema.json. DO NOT EDIT.

package events

type AgentState string

const (
	AgentIdle      AgentState = "idle"
	AgentListening AgentState = "listening"
	AgentThinking  AgentState = "thinking"
	AgentSpeaking  AgentState = "speaking"
)

// AllAgentStates is every member, in schema order.
var AllAgentStates = []AgentState{
	AgentIdle,
	AgentListening,
	AgentThinking,
	AgentSpeaking,
}

func (v AgentState) Valid() bool {
	for _, m := range AllAgentStates {
		if v == m {
			return true
		}
	}
	return false
}
