// Code generated by tools/enumgen from schemas/events/v1/envelope.schema.json. DO NOT EDIT.

package events

type EventType string

const (
	EventSessionCreated           EventType = "session.created"
	EventSessionEnded             EventType = "session.ended"
	EventSessionSignal            EventType = "session.signal"
	EventConnectionEstablished    EventType = "connection.established"
	EventConnectionLost           EventType = "connection.lost"
	EventConnectionRestored       EventType = "connection.restored"
	EventAgentDispatched          EventType = "agent.dispatched"
	EventAgentStateChanged        EventType = "agent.state_changed"
	EventAgentHandoffRequested    EventType = "agent.handoff_requested"
	EventTranscriptPartial        EventType = "transcript.partial"
	EventTranscriptFinal          EventType = "transcript.final"
	EventTranscriptVersionCreated EventType = "transcript.version_created"
	EventTranslationFinal         EventType = "translation.final"
	EventRecordingStarted         EventType = "recording.started"
	EventRecordingCompleted       EventType = "recording.completed"
	EventRecordingSealed          EventType = "recording.sealed"
	EventProviderDegraded         EventType = "provider.degraded"
	EventProviderFailedOver       EventType = "provider.failed_over"
	EventPolicyViolation          EventType = "policy.violation"
	EventBudgetExceeded           EventType = "budget.exceeded"
)

// AllEventTypes is every member, in schema order.
var AllEventTypes = []EventType{
	EventSessionCreated,
	EventSessionEnded,
	EventSessionSignal,
	EventConnectionEstablished,
	EventConnectionLost,
	EventConnectionRestored,
	EventAgentDispatched,
	EventAgentStateChanged,
	EventAgentHandoffRequested,
	EventTranscriptPartial,
	EventTranscriptFinal,
	EventTranscriptVersionCreated,
	EventTranslationFinal,
	EventRecordingStarted,
	EventRecordingCompleted,
	EventRecordingSealed,
	EventProviderDegraded,
	EventProviderFailedOver,
	EventPolicyViolation,
	EventBudgetExceeded,
}

func (v EventType) Valid() bool {
	for _, m := range AllEventTypes {
		if v == m {
			return true
		}
	}
	return false
}
