// Code generated by tools/enumgen from schemas/errors/v1/error.schema.json. DO NOT EDIT.

package errs

type ErrorCode string

const (
	CodeInvalidConfig         ErrorCode = "invalid_config"
	CodeUnsupportedCapability ErrorCode = "unsupported_capability"
	CodeResidencyViolation    ErrorCode = "residency_violation"
	CodeConsentRequired       ErrorCode = "consent_required"
	CodePrivacyModeForbids    ErrorCode = "privacy_mode_forbids"
	CodeQuotaExceeded         ErrorCode = "quota_exceeded"
	CodeBudgetExceeded        ErrorCode = "budget_exceeded"
	CodeRateLimited           ErrorCode = "rate_limited"
	CodeAuthenticationFailed  ErrorCode = "authentication_failed"
	CodeProviderUnavailable   ErrorCode = "provider_unavailable"
	CodeProviderTimeout       ErrorCode = "provider_timeout"
	CodeStreamClosed          ErrorCode = "stream_closed"
	CodeCancelled             ErrorCode = "cancelled"
	CodeInternal              ErrorCode = "internal"
)

// AllErrorCodes is every member, in schema order.
var AllErrorCodes = []ErrorCode{
	CodeInvalidConfig,
	CodeUnsupportedCapability,
	CodeResidencyViolation,
	CodeConsentRequired,
	CodePrivacyModeForbids,
	CodeQuotaExceeded,
	CodeBudgetExceeded,
	CodeRateLimited,
	CodeAuthenticationFailed,
	CodeProviderUnavailable,
	CodeProviderTimeout,
	CodeStreamClosed,
	CodeCancelled,
	CodeInternal,
}

func (v ErrorCode) Valid() bool {
	for _, m := range AllErrorCodes {
		if v == m {
			return true
		}
	}
	return false
}
