// Code generated by tools/enumgen from schemas/errors/v1/error.schema.json. DO NOT EDIT.

package errs

type Stage string

const (
	StageVAD           Stage = "vad"
	StageSTT           Stage = "stt"
	StageTurnDetection Stage = "turn_detection"
	StageContext       Stage = "context"
	StageLLM           Stage = "llm"
	StageTools         Stage = "tools"
	StageSpeechPlanner Stage = "speech_planner"
	StageTTS           Stage = "tts"
	StageEgress        Stage = "egress"
	StageSeal          Stage = "seal"
	StageTransport     Stage = "transport"
	StageControl       Stage = "control"
)

// AllStages is every member, in schema order.
var AllStages = []Stage{
	StageVAD,
	StageSTT,
	StageTurnDetection,
	StageContext,
	StageLLM,
	StageTools,
	StageSpeechPlanner,
	StageTTS,
	StageEgress,
	StageSeal,
	StageTransport,
	StageControl,
}

func (v Stage) Valid() bool {
	for _, m := range AllStages {
		if v == m {
			return true
		}
	}
	return false
}
