global:
  scrape_interval: 5s

scrape_configs:
  - job_name: dafter-control
    static_configs:
      - targets: ["control:8080"]
  - job_name: livekit
    static_configs:
      - targets: ["livekit:6789"]
  - job_name: dafter-agent
    static_configs:
      - targets: ["10.213.0.1:9464"]
