"""Generated by tools/enumgen from schemas/. DO NOT EDIT."""

from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    INVALID_CONFIG = "invalid_config"
    UNSUPPORTED_CAPABILITY = "unsupported_capability"
    RESIDENCY_VIOLATION = "residency_violation"
    CONSENT_REQUIRED = "consent_required"
    PRIVACY_MODE_FORBIDS = "privacy_mode_forbids"
    QUOTA_EXCEEDED = "quota_exceeded"
    BUDGET_EXCEEDED = "budget_exceeded"
    RATE_LIMITED = "rate_limited"
    AUTHENTICATION_FAILED = "authentication_failed"
    PROVIDER_UNAVAILABLE = "provider_unavailable"
    PROVIDER_TIMEOUT = "provider_timeout"
    STREAM_CLOSED = "stream_closed"
    CANCELLED = "cancelled"
    INTERNAL = "internal"

class Stage(StrEnum):
    VAD = "vad"
    STT = "stt"
    TURN_DETECTION = "turn_detection"
    CONTEXT = "context"
    LLM = "llm"
    TOOLS = "tools"
    SPEECH_PLANNER = "speech_planner"
    TTS = "tts"
    EGRESS = "egress"
    SEAL = "seal"
    TRANSPORT = "transport"
    CONTROL = "control"

class EventType(StrEnum):
    SESSION_CREATED = "session.created"
    SESSION_ENDED = "session.ended"
    SESSION_SIGNAL = "session.signal"
    CONNECTION_ESTABLISHED = "connection.established"
    CONNECTION_LOST = "connection.lost"
    CONNECTION_RESTORED = "connection.restored"
    AGENT_DISPATCHED = "agent.dispatched"
    AGENT_STATE_CHANGED = "agent.state_changed"
    AGENT_HANDOFF_REQUESTED = "agent.handoff_requested"
    TRANSCRIPT_PARTIAL = "transcript.partial"
    TRANSCRIPT_FINAL = "transcript.final"
    TRANSCRIPT_VERSION_CREATED = "transcript.version_created"
    TRANSLATION_FINAL = "translation.final"
    RECORDING_STARTED = "recording.started"
    RECORDING_COMPLETED = "recording.completed"
    RECORDING_SEALED = "recording.sealed"
    PROVIDER_DEGRADED = "provider.degraded"
    PROVIDER_FAILED_OVER = "provider.failed_over"
    POLICY_VIOLATION = "policy.violation"
    BUDGET_EXCEEDED = "budget.exceeded"

class AgentState(StrEnum):
    IDLE = "idle"
    LISTENING = "listening"
    THINKING = "thinking"
    SPEAKING = "speaking"

class Role(StrEnum):
    PARTICIPANT = "participant"
    PRESENTER = "presenter"
    OBSERVER = "observer"
    AGENT = "agent"
    RECORDER = "recorder"

class Channel(StrEnum):
    WEBRTC = "webrtc"
    TELEPHONY = "telephony"
    LONG_FORM = "long_form"

class PrivacyMode(StrEnum):
    OPEN = "open"
    SEALED = "sealed"
    TRUSTED_AGENT = "trusted_agent"

class AgentMode(StrEnum):
    CASCADED = "cascaded"
    HALF_CASCADE = "half_cascade"
    SPEECH_TO_SPEECH = "speech_to_speech"

class TurnStrategy(StrEnum):
    AUTO = "auto"
    VAD = "vad"
    PROVIDER_ENDPOINTING = "provider_endpointing"
    SEMANTIC = "semantic"
    SERVER_VAD = "server_vad"
    MANUAL = "manual"

class EgressLayout(StrEnum):
    TRACK = "track"
    TRACK_COMPOSITE = "track_composite"
    ROOM_COMPOSITE = "room_composite"

class RecordingStart(StrEnum):
    SESSION_CREATE = "session_create"
    FIRST_PUBLISH = "first_publish"
