import unittest

from agent_rules.checks.comments import comment_violations


def flagged_lines(path: str, text: str) -> list[int]:
    return [violation.line for violation in comment_violations(path, text)]


class GoCommentTest(unittest.TestCase):
    def test_flags_line_and_block_comments(self) -> None:
        source = "package a\n\n// explains\nvar x = 1 /* inline */\n"
        self.assertEqual(flagged_lines("a.go", source), [3, 4])

    def test_ignores_slashes_inside_strings_runes_and_raw_strings(self) -> None:
        source = "package a\n\nvar u = \"http://x\"\nvar r = '/'\nvar t = `a // b\n/* c */`\n"
        self.assertEqual(flagged_lines("a.go", source), [])

    def test_allows_directives(self) -> None:
        source = (
            "//go:build linux\n\npackage a\n\n"
            "//go:embed x\nvar x string //nolint:gochecknoglobals\n"
        )
        self.assertEqual(flagged_lines("a.go", source), [])

    def test_skips_generated_files(self) -> None:
        source = "// Code generated by enumgen. DO NOT EDIT.\n\npackage a\n\n// note\n"
        self.assertEqual(flagged_lines("a_gen.go", source), [])


class PythonCommentTest(unittest.TestCase):
    def test_flags_comments_but_not_hashes_in_strings(self) -> None:
        source = 'value = "#not"\n# explains\nother = 1  # trailing\n'
        self.assertEqual(flagged_lines("a.py", source), [2, 3])

    def test_allows_directives_shebang_and_encoding(self) -> None:
        source = "#!/usr/bin/env python3\n# -*- coding: utf-8 -*-\nimport os  # noqa: F401\n"
        self.assertEqual(flagged_lines("a.py", source), [])


class ScriptCommentTest(unittest.TestCase):
    def test_ignores_regex_literals_and_template_strings(self) -> None:
        source = "const a = s.replace(/\\//g, '~1');\nconst b = `x // y`;\nconst c = 4 / 2;\n"
        self.assertEqual(flagged_lines("a.js", source), [])

    def test_flags_comments(self) -> None:
        source = "const a = 1; // trailing\n/* block */\n"
        self.assertEqual(flagged_lines("a.mjs", source), [1, 2])

    def test_other_languages_are_not_checked(self) -> None:
        self.assertEqual(flagged_lines("a.sh", "# shell\n"), [])


if __name__ == "__main__":
    unittest.main()
